# Generated by Django 3.0.5 on 2020-05-07 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ads',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=48, verbose_name='عنوان')),
                ('body', models.TextField(verbose_name='توضیحات')),
                ('price', models.BigIntegerField(verbose_name='قیمت')),
                ('img', models.ImageField(upload_to='img')),
            ],
        ),
    ]
